import Link from 'next/link';

const features = [
  ['One-click capture','Capture the candidate you are already viewing, without copying fields by hand.'],
  ['Duplicate protection','Normalize profile URLs and warn before the same candidate enters your sourcing list twice.'],
  ['Spreadsheet ready','Export clean CSV now; automatic Google Sheets sync is the first Pro integration.']
];

export default function Home(){return <main><div className="shell"><nav className="nav"><div className="brand">RecruitMerge</div><Link className="pill" href="/login">Sign in</Link></nav><section className="hero"><div><div className="eyebrow">Recruiting productivity</div><h1>Recruiting spreadsheets without the data entry.</h1><p>Save candidates while you source. RecruitMerge turns each profile into a clean, deduplicated candidate record—ready for your spreadsheet.</p><div className="actions"><Link className="button" href="/login">Start private beta</Link><a className="button secondary" href="#how">See how it works</a></div></div><div className="card mock"><div className="mockhead"><strong>RecruitMerge</strong><span style={{fontSize:12,color:'#6d7279'}}>Candidate detected</span></div><div className="candidate"><h3>Jane Smith</h3><p>Senior Product Designer</p><p>Acme · Orlando, FL</p><div className="field"><div className="label">Job</div><div className="input">Senior Designer</div></div><div className="field"><div className="label">Notes</div><div className="input">Strong B2B experience</div></div><div className="save">Save candidate</div></div></div></section><section id="how" className="section"><h2>A tiny tool for a repetitive job.</h2><div className="grid">{features.map(([h,p])=><div className="card feature" key={h}><h3>{h}</h3><p>{p}</p></div>)}</div></section><section id="beta" className="section"><div className="card feature"><h2>Private beta</h2><p>The first build is focused on candidate capture, clean exports, and duplicate prevention. Billing comes after real recruiters confirm the workflow.</p></div></section></div></main>}
